name: Publish

on:
  push:
    branches:
      - main

jobs:
  charm:
    name: Charm
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install yq
        sudo pip3 install charmcraft==1.0.0

    - name: Publish charm
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies

        CS_URL="cs:~kubeflow-charmers/kubeflow-profiles"

        charmcraft build

        RESOURCES=""
        for resource in kfam-image profile-image; do
          echo Preparing resource: $resource
          image=$(yq eval ".resources.$resource.upstream-source" metadata.yaml)
          echo Pulling image $image
          docker pull $image
          RESOURCES="$RESOURCES --resource $resource=$image"
        done 
        
        charm push ./*.charm $CS_URL $RESOURCES

        REVISION=$(charm show $CS_URL --channel unpublished --format yaml | yq e .id-revision.Revision -)
        OCI_VERSION=$(charm list-resources $CS_URL --format yaml --channel unpublished | yq e .0.revision -)
        charm release \
            --channel edge \
            $RESOURCES \
            $CS_URL-$REVISION
